services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "4200:4000"
    networks:
      - app-network

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    container_name: mongo
    build: ./database
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
