services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "4200:4000"
    networks:
      - app-network      

networks:
  app-network:
    driver: bridge
